/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef, useState} from 'react'
import {useGLTF, useTexture} from '@react-three/drei'
import {Euler, Vector3} from "three";
import {useFrame} from "@react-three/fiber";

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/test.gltf')
  const myMesh = React.useRef();
  const [active, setActive] = useState(false);


  useFrame(({ clock }) => {
    const a = clock.getElapsedTime();
    myMesh.current.rotation.x = a;
  });

  const text = useTexture({
    map: 'Wood062_2K_Color.jpg',
    normalMap: 'Wood062_2K_Normal.jpg',
    roughnessMap: 'Wood062_2K_Roughness.png',
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh ref={myMesh} geometry={nodes.Cube.geometry} material={materials['Wood062_2K_Color.jpg']}>
        {/*<meshStandardMaterial {...text} />*/}
      </mesh>
    </group>
  )
}

useGLTF.preload('/test.gltf')
